### ISSUE TITLE
Feature Request/Bug?: Retain formatting even if link "touches" formatting marks

### ISSUE THREAD

**Issue by ReaderGuy42** [vschroeter/obsidian-virtual-linker#63] opened 2024-09-15 14:49 UTC
![image](https://github.com/user-attachments/assets/7e6c04fe-2bee-4e5a-be4b-313ac90b7121)

If the formatting marks, e.g. `**, ==, *` "touch" the virtual link, the formatting is lost for the link. However, if the link is in the middle of the formatted text, it's correctly highlighted, bold, etc.

Would it be possible to change it so the formatting would be kept even if the virtual link touches the formatting marks?

Thanks!

**Comment by vschroeter** [comment] 2024-09-15 17:27
Duplicate of #59. I'll implement it in the next update

**Closed by vschroeter** 2024-09-15 17:27 UTC
Labels: duplicate
