### ISSUE TITLE
A great plugin but a minor bug, for help

### ISSUE THREAD

**Issue by nanjingman** [vschroeter/obsidian-virtual-linker#16] opened 2024-07-11 00:50 UTC
![image](https://github.com/vschroeter/obsidian-virtual-linker/assets/101070393/7aa73611-cbb1-4890-bceb-6aab5055bfdb)

Thanks!

**Comment by calmwaves111** [comment] 2024-07-14 14:54
I also encountered a similar problem. This seems to be a word segmentation bug, especially for Chinese speakers
If I turn off Match only whole words on the settings page, some unreasonable virtual links will appear
![image](https://github.com/user-attachments/assets/0e1ab551-b743-4041-ba97-ada530264774)
It is difficult for me to provide you with a screenshot of the notes page because my notes are in Chinese.
And I'm sure this bug wasn't there before 1.3.0

**Comment by calmwaves111** [comment] 2024-07-14 15:26
All the links here are not expected, but I'm not sure you can understand this Chinese note.
![image](https://github.com/user-attachments/assets/59d98d41-b826-4c46-8792-3301ea3c4234)
For example, the first character 【件】links to a fileA, whose aliases is 【创建新文件】，I guess the link is on because there is also a character 【件】, but it is wrong.

**Comment by quelsemme** [comment] 2024-07-29 01:30
I have the same problem.
"Match whole words" improves it in some cases but not others.

One case is with something like a name.
Doe, J

"J" ends up being linked.

Another case is with words

"Metadata" as a heading linked every letter separately.

**Comment by JungJas** [comment] 2024-07-29 09:50
I love the idea behind this plugin! Unfortunately I'm running into the same issue as reported here. You can see an example in the attached image. I don't have any markdown files named "1", "a", "s", "t"... It seems to be an issue specifically with single letter words.

![Screenshot 2024-07-29 at 11 50 34](https://github.com/user-attachments/assets/d5c5b92d-d585-4c07-89c8-df5f01eec159)

**Comment by vschroeter** [comment] 2024-07-29 10:49
I still could not reproduce this, but I have an idea of what might be causing it.
I've added a fix in [Version 1.4.4](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.4).

If the problem sill persists, could you try turning off the "Include aliases" option in the settings?

If then the problem still persists, I would really appreciate it, if someone can attach a minimal example vault having the problem, so that I can take a look.

**Comment by GevatterWolf** [comment] 2024-07-29 11:31
Version 1.4.4 solved the issue for me. Thank you!

**Comment by calmwaves111** [comment] 2024-07-29 12:08
Thank you for your hard work. Version 1.4.4 has solved this problem. 
I hope it can be merged into the master branch because the update of 1.4.4 cannot be detected in the plugin market now.

**Comment by vschroeter** [comment] 2024-07-29 13:43
Happy to hear, that it worked! 
It is now also installable via the plugin market.

@calmwaves111, I assume you have toggled the correct settings to show it and there also is still an entry in the `Virtual Link Suffix` textfield? If so, feel free to open another issue and provide details of the behaviour :) 
For me, the suffix is still fine.

**Closed by vschroeter** 2024-07-29 13:43 UTC

**Comment by calmwaves111** [comment] 2024-07-29 13:48
> Happy to hear, that it worked! It is now also installable via the plugin market.
> 
> @calmwaves111, I assume you have toggled the correct settings to show it and there also is still an entry in the `Virtual Link Suffix` textfield? If so, feel free to open another issue and provide details of the behaviour :) For me, the suffix is still fine.

Yes, you are right，After I reinstalled the plugin via the plugin market, everything was okay including 【Virtual link suffix】 Thank you again for your hard work.
